// End-to-end tests of the procedure against fixtures with KNOWN answers (generated by
// fixtures/spreadsheet/generate.mjs). The model is MOCKED here: a fake InferenceClient.
import { readFileSync } from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";
import type { ProcedureOutcome } from "../../../../shared/contracts";
import { procedures, spreadsheetCompare } from "./index";
import { RULES_DEFAULT, SAMPLES, doneOrThrow, fakeAi, fx, makeCtx, readClasses } from "./testkit";

const expected = (name: string) => JSON.parse(readFileSync(fx(`expected/${name}`), "utf8"));
const run = (ctx: Awaited<ReturnType<typeof makeCtx>>) => spreadsheetCompare.run(ctx);

async function runDone(a: string, b: string, answers: Record<string, string> = RULES_DEFAULT) {
  const ctx = await makeCtx({ fileA: a, fileB: b, answers });
  const out = doneOrThrow(await run(ctx));
  return { ctx, out };
}

function expectCounts(out: Extract<ProcedureOutcome, { kind: "done" }>, exp: { counts: Record<string, number> }) {
  expect((out.report as { counts: Record<string, number> }).counts).toEqual(exp.counts);
}

async function expectRows(file: string, exp: ReturnType<typeof expected>) {
  const c = await readClasses(file);
  expect(c.matched).toEqual(exp.rows.matched.map((p: { a: number; b: number }) => [p.a, p.b]));
  expect(c.onlyA).toEqual(exp.rows.onlyA);
  expect(c.onlyB).toEqual(exp.rows.onlyB);
  expect(c.dupA).toEqual(exp.rows.duplicateA);
  expect(c.dupB).toEqual([]);
  expect(c.ambA).toEqual(exp.rows.ambiguousA);
  expect(c.ambB).toEqual(exp.rows.ambiguousB);
}

function check(out: Extract<ProcedureOutcome, { kind: "done" }>, id: string) {
  return out.checks.find((c) => c.id === id);
}

describe("definition", () => {
  it("is exported and honest", () => {
    expect(procedures).toHaveLength(1);
    const def = procedures[0]!;
    expect(def).toMatchObject({ id: "spreadsheet-compare", pack: "bookkeeping", revision: "1" });
    expect(def.inputs.map((i) => [i.key, i.kind, i.accept])).toEqual([
      ["fileA", "file", [".csv", ".xlsx"]],
      ["fileB", "file", [".csv", ".xlsx"]],
    ]);
    const text = [def.supports, ...def.limits].join(" ");
    expect(text).toMatch(/50,000/);
    expect(text).toMatch(/not the formulas/);
    expect(text).toMatch(/macros/);
    expect(text).not.toContain("—");
  });
});

describe("mixed CSV fixture (31 matched, 3 only-A, 2 only-B, 2 duplicates in A, 1 ambiguous group)", () => {
  it("asks the rule questions first, each with a one-click suggestion", async () => {
    const ctx = await makeCtx({ fileA: fx("mixed-a.csv"), fileB: fx("mixed-b.csv") });
    const out = await run(ctx);
    expect(out.kind).toBe("needs-input");
    if (out.kind !== "needs-input") return;
    expect(out.questions.map((q) => q.id)).toEqual(["rule.period", "rule.amountTolerance", "rule.dateToleranceDays"]);
    expect(out.questions.map((q) => q.suggested)).toEqual(["overlap", "0.00", "3"]);
    expect(ctx.written).toHaveLength(0);
    expect(ctx.fake.calls).toHaveLength(0);
  });

  it("does not re-ask what the answers already hold", async () => {
    const ctx = await makeCtx({ fileA: fx("mixed-a.csv"), fileB: fx("mixed-b.csv"), answers: { "rule.amountTolerance": "0.00", "rule.dateToleranceDays": "3" } });
    const out = await run(ctx);
    expect(out.kind === "needs-input" && out.questions.map((q) => q.id)).toEqual(["rule.period"]);
  });

  it("classifies every row exactly as constructed, with exact cent totals", async () => {
    const exp = expected("mixed.json");
    const { ctx, out } = await runDone(fx("mixed-a.csv"), fx("mixed-b.csv"));
    expectCounts(out, exp);
    await expectRows(ctx.written[0]!.path, exp);

    const r = out.report as { totalsCents: Record<string, number> & { byClass: { key: string; aCents: number; bCents: number; effectCents: number }[] } };
    expect(r.totalsCents.a).toBe(exp.totalsCents.a);
    expect(r.totalsCents.b).toBe(exp.totalsCents.b);
    expect(r.totalsCents.difference).toBe(exp.totalsCents.difference);
    const by = Object.fromEntries(r.totalsCents.byClass.map((x) => [x.key, x]));
    expect(by.matched!.aCents).toBe(exp.totalsCents.matchedA);
    expect(by.matched!.bCents).toBe(exp.totalsCents.matchedB);
    expect(by.onlyA!.aCents).toBe(exp.totalsCents.onlyA);
    expect(by.onlyB!.bCents).toBe(exp.totalsCents.onlyB);
    expect(by.dupA!.aCents).toBe(exp.totalsCents.duplicateA);
    expect(by.ambiguous!.aCents).toBe(exp.totalsCents.ambiguousA);
    expect(by.ambiguous!.bCents).toBe(exp.totalsCents.ambiguousB);
    // The class effects explain the whole difference, in whole cents.
    expect(r.totalsCents.byClass.reduce((s, x) => s + x.effectCents, 0)).toBe(exp.totalsCents.difference);
  });

  it("accounts for every record: matched*2 + onlyA + onlyB + dupA + dupB + ambiguousA + ambiguousB == totalA + totalB", async () => {
    const { out } = await runDone(fx("mixed-a.csv"), fx("mixed-b.csv"));
    const c = (out.report as { counts: Record<string, number> }).counts as Record<string, number>;
    const placed = c.matched! * 2 + c.onlyA! + c.onlyB! + c.duplicateA! + c.duplicateB! + c.ambiguousA! + c.ambiguousB!;
    expect(placed).toBe(c.totalA! + c.totalB!);
    expect(check(out, "account-for-every-record")?.status).toBe("pass");
    expect(check(out, "difference-explained")?.status).toBe("pass");
  });

  it("writes a workbook that reopens and validates, with source file and row on every line", async () => {
    const { ctx, out } = await runDone(fx("mixed-a.csv"), fx("mixed-b.csv"));
    expect(check(out, "output-reopened")?.status).toBe("pass");
    expect(out.outputs).toHaveLength(1);
    expect(out.outputs[0]).toMatchObject({ kind: "xlsx" });
    const ExcelJS = (await import("exceljs")).default;
    const wb = new ExcelJS.Workbook();
    await wb.xlsx.readFile(out.outputs[0]!.path);
    expect(wb.worksheets.map((w) => w.name)).toEqual(["Summary", "Matched", "Only in A", "Only in B", "Listed twice", "Not sure", "About this comparison"]);
    const onlyA = wb.getWorksheet("Only in A")!;
    expect(onlyA.getRow(1).values).toEqual(expect.arrayContaining(["Source", "File", "Row", "All original values"]));
    expect(String(onlyA.getRow(2).getCell(2).value)).toBe("mixed-a.csv");
    expect(String(onlyA.getRow(2).getCell(11).value)).toContain("Description:");
    // Values only: the app cannot verify formulas, so none may be written.
    for (const ws of wb.worksheets) ws.eachRow((row) => row.eachCell((cell) => expect(typeof cell.value === "object" && cell.value !== null && "formula" in cell.value).toBe(false)));
    expect(ctx.written[0]!.path).toBe(out.outputs[0]!.path);
  });

  it("reads quoted, parenthesised and currency-prefixed amounts, BOM, CRLF and trailing blank lines", async () => {
    const { out } = await runDone(fx("mixed-a.csv"), fx("mixed-b.csv"));
    const f = (out.report as { files: { a: { rows: number; currency: string | null; skipped: number }; b: { rows: number; skipped: number } } }).files;
    expect(f.a).toMatchObject({ rows: 37, currency: "PHP", skipped: 0 });
    expect(f.b).toMatchObject({ rows: 35, skipped: 0 });
  });

  it("offers a staged change to file A: csv-set-cells with two appended columns and a useful preview", async () => {
    const exp = expected("mixed.json");
    const { out } = await runDone(fx("mixed-a.csv"), fx("mixed-b.csv"));
    expect(out.proposals).toHaveLength(1);
    const p = out.proposals[0]!;
    expect(p.target).toBe(fx("mixed-a.csv"));
    expect(p.edits).toHaveLength(1);
    const e = p.edits[0]!;
    expect(e.op).toBe("csv-set-cells");
    if (e.op !== "csv-set-cells") return;
    expect(e.cells).toEqual([]);
    expect(e.appendColumns?.map((c) => c.header)).toEqual(["NONON status", "NONON note"]);
    const [status, note] = e.appendColumns!;
    expect(status!.values).toHaveLength(37);
    expect(note!.values).toHaveLength(37);
    const at = (row: number) => status!.values[row - 2];
    for (const r of exp.rows.onlyA) expect(at(r)).toBe("only here");
    for (const r of exp.rows.duplicateA) expect(at(r)).toBe("listed twice");
    for (const r of exp.rows.ambiguousA) expect(at(r)).toBe("check");
    for (const m of exp.rows.matched) expect(at(m.a)).toBe("matched");
    expect(status!.values.filter((v) => v === "matched")).toHaveLength(31);
    expect(note!.values[exp.rows.matched[0].a - 2]).toBe(`Matches row ${exp.rows.matched[0].b} in mixed-b.csv`);

    expect(p.reason).toMatch(/NONON|Adds two columns/);
    const { before, after, highlights, title } = p.preview;
    expect(title).toContain("mixed-a.csv");
    expect(Array.isArray(before) && Array.isArray(after)).toBe(true);
    const b = before as string[][];
    const a = after as string[][];
    expect(a.length).toBe(b.length);
    expect(a.length).toBeLessThanOrEqual(13);
    expect(a[0]!.slice(-2)).toEqual(["NONON status", "NONON note"]);
    expect(a[0]!.length).toBe(b[0]!.length + 2);
    // Rows that need attention come first, so the review shows what matters.
    const shown = a.slice(1).map((r) => r[a[0]!.length - 2]);
    expect(shown.filter((s) => s !== "matched").length).toBe(6);
    for (const h of highlights!) {
      expect(h.row).toBeLessThan(a.length);
      expect(h.col).toBeLessThan(a[0]!.length);
      expect(h.col).toBeGreaterThanOrEqual(a[0]!.length - 2);
    }
    expect(highlights!.length).toBe(2 * a.length);
    expect(p.checks.map((c) => c.id)).toEqual(["append-only", "rows-annotated"]);
    expect(check(out, "proposal-offered")?.status).toBe("pass");
  });

  it("writes nothing to the originals", async () => {
    const before = readFileSync(fx("mixed-a.csv"));
    await runDone(fx("mixed-a.csv"), fx("mixed-b.csv"));
    expect(readFileSync(fx("mixed-a.csv")).equals(before)).toBe(true);
  });

  it("makes one explanation call and labels it as model output; summary carries the real numbers", async () => {
    const { ctx, out } = await runDone(fx("mixed-a.csv"), fx("mixed-b.csv"));
    expect(ctx.fake.calls).toHaveLength(1);
    expect(ctx.fake.calls[0]!.jsonSchema).toBeTruthy();
    expect((out.report as { explanation: { source: string } }).explanation.source).toBe("model");
    expect(out.summary).toContain("31 pairs of rows match");
    expect(out.summary).toContain("Matched pairs: 31");
    expect(out.summary).toContain("Only in A: 3");
    expect(out.summary).toContain("calculated by NONON, not by AI");
    expect(out.summary).not.toContain("—");
    expect(check(out, "ai-explanation")).toBeUndefined();
  });

  it("the prompt is capped and contains computed numbers, not the raw tables", async () => {
    const { ctx } = await runDone(fx("mixed-a.csv"), fx("mixed-b.csv"));
    const prompt = ctx.fake.calls[0]!.messages.map((m) => m.content).join("\n");
    expect(prompt.length).toBeLessThan(5500);
    expect(prompt).toContain("Matched pairs: 31");
    expect(prompt).not.toContain("INV-1028");
  });
});

describe("explanation validation and fallback (mocked model)", () => {
  it("retries once on invalid output, then uses a standard summary and says so", async () => {
    const ai = fakeAi((_req, n) => (n === 1 ? "not json at all" : '{"summary":"too short","checkFirst":[]}'));
    const ctx = await makeCtx({ fileA: fx("mixed-a.csv"), fileB: fx("mixed-b.csv"), answers: RULES_DEFAULT, ai });
    const out = doneOrThrow(await run(ctx));
    expect(ai.calls).toHaveLength(2);
    expect(ai.calls[1]!.messages.at(-1)!.content).toMatch(/Reply again with only the JSON/);
    expect(check(out, "ai-explanation")).toMatchObject({ status: "warn", label: "The AI could not write the explanation, so a standard summary is shown" });
    expect((out.report as { explanation: { source: string } }).explanation.source).toBe("template");
    expect(out.summary.startsWith("Standard summary (the AI could not write one this time)")).toBe(true);
    expect(out.summary).toContain("Matched pairs: 31");
  });

  it("recovers when the retry is valid", async () => {
    const ai = fakeAi((_req, n) =>
      n === 1 ? "oops" : JSON.stringify({ summary: "31 pairs match. Look at the unmatched rows listed in the workbook.", checkFirst: ["Open the Only in A sheet."] }),
    );
    const ctx = await makeCtx({ fileA: fx("mixed-a.csv"), fileB: fx("mixed-b.csv"), answers: RULES_DEFAULT, ai });
    const out = doneOrThrow(await run(ctx));
    expect(ai.calls).toHaveLength(2);
    expect((out.report as { explanation: { source: string; attempts: number } }).explanation).toMatchObject({ source: "model", attempts: 2 });
    expect(check(out, "ai-explanation")).toBeUndefined();
  });

  it("rejects a model that invents figures", async () => {
    const ai = fakeAi(() => JSON.stringify({ summary: "You are missing about 48,213 pesos in unpaid invoices from last year.", checkFirst: ["Chase the 17 unpaid invoices."] }));
    const ctx = await makeCtx({ fileA: fx("mixed-a.csv"), fileB: fx("mixed-b.csv"), answers: RULES_DEFAULT, ai });
    const out = doneOrThrow(await run(ctx));
    expect(ai.calls).toHaveLength(2);
    expect(ai.calls[1]!.messages.at(-1)!.content).toMatch(/numbers that were not given/);
    expect((out.report as { explanation: { source: string } }).explanation.source).toBe("template");
    expect(out.summary).not.toContain("48,213");
  });

  it("rejects a model that points at rows that are not in the list it was shown", async () => {
    const ai = fakeAi(() => JSON.stringify({ summary: "31 pairs match and a few rows need a look.", checkFirst: ["Compare A row 999 with B row 998."] }));
    const ctx = await makeCtx({ fileA: fx("mixed-a.csv"), fileB: fx("mixed-b.csv"), answers: RULES_DEFAULT, ai });
    const out = doneOrThrow(await run(ctx));
    expect(ai.calls).toHaveLength(2);
    expect(ai.calls[1]!.messages.at(-1)!.content).toMatch(/not given: 999, 998|not in the item list: 999, 998/);
    expect((out.report as { explanation: { source: string } }).explanation.source).toBe("template");
  });

  it("rejects a listed-looking number that is not a listed row", async () => {
    let stray = 0;
    const ai = fakeAi((req) => {
      const prompt = req.messages[1]!.content;
      const listed = new Set([...prompt.matchAll(/- [AB] row (\d+)/g)].map((m) => Number(m[1])));
      // Pick a number that IS in the facts (so only the row check can catch it) but is not a listed row.
      stray = [31, 37, 35, 3].find((n) => !listed.has(n)) ?? 0;
      return JSON.stringify({ summary: "31 pairs match and a few rows need a look.", checkFirst: [`Compare A row ${stray} first.`] });
    });
    const ctx = await makeCtx({ fileA: fx("mixed-a.csv"), fileB: fx("mixed-b.csv"), answers: RULES_DEFAULT, ai });
    await run(ctx);
    expect(stray).toBeGreaterThan(0);
    expect(ai.calls[1]!.messages.at(-1)!.content).toContain(`not in the item list: ${stray}`);
  });

  it("accepts rows that are in the list", async () => {
    const ai = fakeAi((req) => {
      const prompt = req.messages.map((m) => m.content).join("\n");
      const row = /- (A) row (\d+)/.exec(prompt);
      return JSON.stringify({ summary: "31 pairs match and a few rows need a look.", checkFirst: [`Look at ${row?.[1]} row ${row?.[2]} first.`] });
    });
    const ctx = await makeCtx({ fileA: fx("mixed-a.csv"), fileB: fx("mixed-b.csv"), answers: RULES_DEFAULT, ai });
    const out = doneOrThrow(await run(ctx));
    expect(ai.calls).toHaveLength(1);
    expect((out.report as { explanation: { source: string } }).explanation.source).toBe("model");
  });

  it("with nothing to review, the action line is the fixed truth, not whatever the model padded in", async () => {
    const ai = fakeAi(() => JSON.stringify({ summary: "All 40 pairs of rows match.", checkFirst: ["Look at the summary row in clean-a.csv."] }));
    const ctx = await makeCtx({ fileA: fx("clean-a.csv"), fileB: fx("clean-b.csv"), answers: RULES_DEFAULT, ai });
    const out = doneOrThrow(await run(ctx));
    expect((out.report as { explanation: { checkFirst: string[]; source: string } }).explanation).toMatchObject({
      source: "model",
      checkFirst: ["Nothing needs fixing. Keep the comparison workbook with your records."],
    });
    expect(out.summary).not.toContain("summary row");
  });

  it("survives the model server being down", async () => {
    const ai = fakeAi(() => {
      throw new Error("connect ECONNREFUSED");
    });
    const ctx = await makeCtx({ fileA: fx("clean-a.csv"), fileB: fx("clean-b.csv"), answers: RULES_DEFAULT, ai });
    const out = doneOrThrow(await run(ctx));
    expect(check(out, "ai-explanation")?.status).toBe("warn");
    expect(out.outputs).toHaveLength(1);
  });

  it("strips em dashes the model writes", async () => {
    const ai = fakeAi(() => JSON.stringify({ summary: "All 40 pairs of rows match — nothing needs fixing here.", checkFirst: ["Keep the workbook."] }));
    const ctx = await makeCtx({ fileA: fx("clean-a.csv"), fileB: fx("clean-b.csv"), answers: RULES_DEFAULT, ai });
    const out = doneOrThrow(await run(ctx));
    expect(out.summary).not.toContain("—");
    expect(out.summary).toContain("All 40 pairs of rows match, nothing needs fixing here.");
  });
});

describe("clean fixture", () => {
  it("40 vs 40: everything matches, no discrepancies", async () => {
    const exp = expected("clean.json");
    const { ctx, out } = await runDone(fx("clean-a.csv"), fx("clean-b.csv"));
    expectCounts(out, exp);
    expect(exp.counts.matched).toBe(40);
    const c = await readClasses(ctx.written[0]!.path);
    expect(c.matched).toHaveLength(40);
    expect([c.onlyA, c.onlyB, c.dupA, c.dupB, c.ambA, c.ambB].every((x) => x.length === 0)).toBe(true);
    expect((out.report as { totalsCents: { difference: number } }).totalsCents.difference).toBe(0);
    expect(out.proposals[0]!.edits[0]).toMatchObject({ op: "csv-set-cells" });
    expect(check(out, "weak-matches")).toBeUndefined();
  });
});

describe("ambiguous headers fixture", () => {
  it("asks which column is which, with the right suggestion for each", async () => {
    const exp = expected("ambiguous-headers.json");
    const ctx = await makeCtx({ fileA: fx("ambiguous-a.csv"), fileB: fx("ambiguous-b.csv"), answers: RULES_DEFAULT });
    const out = await run(ctx);
    expect(out.kind).toBe("needs-input");
    if (out.kind !== "needs-input") return;
    const byId = Object.fromEntries(out.questions.map((q) => [q.id, q]));
    expect(Object.keys(byId).sort()).toEqual(["map.a.amount", "map.a.date", "map.a.description"]);
    for (const [id, header] of Object.entries(exp.questions as Record<string, string>)) {
      expect(byId[id]!.suggested).toBe(header);
      expect(byId[id]!.kind).toBe("choice");
      expect(byId[id]!.options!.map((o) => o.value)).toContain(header);
    }
    expect(byId["map.a.description"]!.options!.at(-1)).toEqual({ value: "__none__", label: "None of these" });
  });

  it("proceeds when the suggestions are accepted and finds the one missing row", async () => {
    const exp = expected("ambiguous-headers.json");
    const answers = { ...RULES_DEFAULT, "map.a.date": "Txn Dt", "map.a.description": "Details", "map.a.amount": "Amt" };
    const { ctx, out } = await runDone(fx("ambiguous-a.csv"), fx("ambiguous-b.csv"), answers);
    expectCounts(out, exp);
    const c = await readClasses(ctx.written[0]!.path);
    expect(c.onlyA).toEqual(exp.rows.onlyA);
  });

  it("ignores a model hint that names a column that does not exist, and still asks", async () => {
    const ai = fakeAi((req) => {
      const props = (req.jsonSchema as { properties?: object } | undefined)?.properties ?? {};
      return "checkFirst" in props ? "{}" : JSON.stringify({ date: "Transaction Posted", description: "Memo Text", reference: "", amount: "Total Cash", debit: "", credit: "" });
    });
    const ctx = await makeCtx({ fileA: fx("ambiguous-a.csv"), fileB: fx("ambiguous-b.csv"), answers: RULES_DEFAULT, ai });
    const out = await run(ctx);
    expect(ai.calls.length).toBeGreaterThan(0);
    expect(out.kind).toBe("needs-input");
    if (out.kind !== "needs-input") return;
    const s = Object.fromEntries(out.questions.map((q) => [q.id, q.suggested]));
    expect(s).toMatchObject({ "map.a.date": "Txn Dt", "map.a.description": "Details", "map.a.amount": "Amt" });
  });

  it("uses a valid model hint only when the values fit that column", async () => {
    const ai = fakeAi((req) => {
      const props = (req.jsonSchema as { properties?: object } | undefined)?.properties ?? {};
      return "checkFirst" in props ? "{}" : JSON.stringify({ date: "Amt", description: "", reference: "", amount: "", debit: "", credit: "" });
    });
    const ctx = await makeCtx({ fileA: fx("ambiguous-a.csv"), fileB: fx("ambiguous-b.csv"), answers: RULES_DEFAULT, ai });
    const out = await run(ctx);
    if (out.kind !== "needs-input") throw new Error("expected needs-input");
    expect(Object.fromEntries(out.questions.map((q) => [q.id, q.suggested]))["map.a.date"]).toBe("Txn Dt");
  });

  it("an unrecognised answer is ignored rather than trusted", async () => {
    const answers = { ...RULES_DEFAULT, "map.a.date": "No Such Column" };
    const ctx = await makeCtx({ fileA: fx("ambiguous-a.csv"), fileB: fx("ambiguous-b.csv"), answers });
    const out = await run(ctx);
    expect(out.kind === "needs-input" && out.questions.map((q) => q.id)).toContain("map.a.date");
  });
});

describe("missing amount column", () => {
  it("stops with a clear message naming the file and the missing column", async () => {
    const exp = expected("missing-column.json");
    const ctx = await makeCtx({ fileA: fx("missing-a.csv"), fileB: fx("missing-b.csv"), answers: RULES_DEFAULT });
    const out = await run(ctx);
    expect(out.kind).toBe("unsupported");
    if (out.kind !== "unsupported") return;
    for (const m of exp.unsupportedMentions) expect(out.reason).toContain(m);
    expect(out.reason).toContain("missing-b.csv");
    expect(out.reason).toContain("Date, Description, Reference, Notes");
    expect(out.suggestion).toBeTruthy();
    expect(ctx.written).toHaveLength(0);
    expect(ctx.fake.calls).toHaveLength(0);
  });
});

describe("day/month ambiguity", () => {
  it("asks which order, suggesting the reading that fits the other file", async () => {
    const ctx = await makeCtx({ fileA: fx("ddmm-a.csv"), fileB: fx("ddmm-b.csv"), answers: RULES_DEFAULT });
    const out = await run(ctx);
    expect(out.kind).toBe("needs-input");
    if (out.kind !== "needs-input") return;
    expect(out.questions.map((q) => q.id)).toEqual(["rule.dateOrder.a"]);
    const q = out.questions[0]!;
    expect(q.suggested).toBe("DMY");
    expect(q.prompt).toContain("02/04/2026");
    expect(q.prompt).toContain("2 Apr 2026");
    expect(q.prompt).toContain("4 Feb 2026");
  });

  it("day first: all 11 match. Month first: the answer changes the result, so it matters", async () => {
    const dmy = await runDone(fx("ddmm-a.csv"), fx("ddmm-b.csv"), { ...RULES_DEFAULT, "rule.dateOrder.a": "DMY" });
    expect((dmy.out.report as { counts: { matched: number } }).counts.matched).toBe(11);
    const mdy = await runDone(fx("ddmm-a.csv"), fx("ddmm-b.csv"), { ...RULES_DEFAULT, "rule.dateOrder.a": "MDY", "rule.period": "all" });
    expect((mdy.out.report as { counts: { matched: number } }).counts.matched).toBeLessThan(11);
  });

  it("does not ask when a day above 12 proves the order", async () => {
    const ctx = await makeCtx({ fileA: fx("ddmm-clear-a.csv"), fileB: fx("ddmm-clear-b.csv"), answers: RULES_DEFAULT });
    const out = doneOrThrow(await run(ctx));
    expect((out.report as { counts: { matched: number } }).counts.matched).toBe(11);
  });
});

describe("XLSX", () => {
  it("gives the same classes as the CSV version of the mixed fixture", async () => {
    const exp = expected("mixed-xlsx.json");
    const { ctx, out } = await runDone(fx("mixed-a.xlsx"), fx("mixed-b.xlsx"));
    expectCounts(out, exp);
    await expectRows(ctx.written[0]!.path, exp);
    expect((out.report as { totalsCents: { a: number; b: number } }).totalsCents).toMatchObject({ a: exp.totalsCents.a, b: exp.totalsCents.b });
    const e = out.proposals[0]!.edits[0]!;
    expect(e.op).toBe("xlsx-set-cells");
    if (e.op !== "xlsx-set-cells") return;
    expect(e.sheet).toBe("Ledger");
    expect(e.appendColumns?.map((c) => c.header)).toEqual(["NONON status", "NONON note"]);
    expect(e.appendColumns![0]!.values).toHaveLength(37);
  });

  it("works across file types (CSV against XLSX)", async () => {
    const exp = expected("mixed.json");
    const { out } = await runDone(fx("mixed-a.csv"), fx("mixed-b.xlsx"));
    expectCounts(out, exp);
  });

  it("a formula with no saved result is warned about, left out, and never recalculated; a cached formula is used", async () => {
    const exp = expected("mixed-xlsx-formula.json");
    const { ctx, out } = await runDone(fx("mixed-a-formula.xlsx"), fx("mixed-b.xlsx"));
    expectCounts(out, exp);
    expect(check(out, "formula-no-result")).toMatchObject({ status: "warn" });
    expect(check(out, "formula-no-result")!.detail).toContain(`D${exp.skippedA[0]}`);
    expect(check(out, "skipped-rows-a")).toMatchObject({ status: "warn" });
    const c = await readClasses(ctx.written[0]!.path);
    expect(c.skipped).toEqual(exp.skippedA);
    expect(c.onlyA).toEqual(exp.rows.onlyA);
    expect(c.matched).toEqual(exp.rows.matched.map((p: { a: number; b: number }) => [p.a, p.b]));
    expect((out.report as { files: { a: { skipped: number } } }).files.a.skipped).toBe(1);
    // The skipped row is still marked in the staged change so the original shows it was not compared.
    const e = out.proposals[0]!.edits[0]!;
    if (e.op !== "xlsx-set-cells") throw new Error("expected xlsx edit");
    const note = e.appendColumns![1]!.values[exp.skippedA[0] - 2];
    expect(String(note)).toContain("Not compared");
  });

  it("warns about unsupported workbook features, still compares, and offers no edit to that workbook", async () => {
    const exp = expected("mixed-xlsx-chart.json");
    const { out } = await runDone(fx("mixed-a-chart.xlsx"), fx("mixed-b.xlsx"));
    expectCounts(out, exp);
    const w = check(out, "unsupported-features");
    expect(w?.status).toBe("warn");
    expect(w?.label).toContain("charts");
    expect(out.proposals).toHaveLength(0);
    expect(check(out, "proposal-offered")).toMatchObject({ status: "warn" });
    expect(out.outputs).toHaveLength(1);
  });

  it("asks which sheet when several hold data, suggesting the one with the most rows", async () => {
    const ctx = await makeCtx({ fileA: fx("multi-sheet-a.xlsx"), fileB: fx("mixed-b.xlsx"), answers: RULES_DEFAULT });
    const out = await run(ctx);
    expect(out.kind).toBe("needs-input");
    if (out.kind !== "needs-input") return;
    expect(out.questions).toHaveLength(1);
    expect(out.questions[0]).toMatchObject({ id: "sheet.a", suggested: "Ledger" });
    expect(out.questions[0]!.options!.map((o) => o.value)).toEqual(["Notes", "Ledger"]);
    const done = await runDone(fx("multi-sheet-a.xlsx"), fx("mixed-b.xlsx"), { ...RULES_DEFAULT, "sheet.a": "Ledger" });
    expectCounts(done.out, expected("mixed.json"));
    expect(done.out.checks.find((c) => c.id === "files-read")?.detail).toContain('sheet "Ledger"');
  });
});

describe("refusals", () => {
  it("needs two files", async () => {
    const ctx = await makeCtx({ fileA: fx("mixed-a.csv"), fileB: fx("mixed-b.csv") });
    ctx.files.fileB = [];
    expect((await run(ctx)).kind).toBe("unsupported");
  });

  it("will not compare a file with itself", async () => {
    const ctx = await makeCtx({ fileA: fx("mixed-a.csv"), fileB: fx("mixed-a.csv") });
    expect((await run(ctx)).kind).toBe("unsupported");
  });

  it("explains unsupported formats", async () => {
    const ctx = await makeCtx({ fileA: fx("expected/mixed.json"), fileB: fx("mixed-b.csv") });
    const out = await run(ctx);
    expect(out.kind === "unsupported" && out.reason).toContain("Excel (.xlsx) and .csv");
  });
});

describe("bookkeeping demo samples", () => {
  const a = path.join(SAMPLES, "expense-report-may-2026.csv");
  const b = path.join(SAMPLES, "bank-export-may-2026.csv");

  it("asks how to compare signs (suggesting opposite) because the bank shows spending as minus", async () => {
    const ctx = await makeCtx({ fileA: a, fileB: b });
    const out = await run(ctx);
    expect(out.kind).toBe("needs-input");
    if (out.kind !== "needs-input") return;
    expect(out.questions.map((q) => q.id)).toEqual(["rule.amountSign", "rule.period", "rule.amountTolerance", "rule.dateToleranceDays"]);
    expect(out.questions[0]!.suggested).toBe("opposite");
  });

  it("finds exactly the planted discrepancies", async () => {
    const exp = JSON.parse(readFileSync(fx("expected/sample-bookkeeping.json"), "utf8"));
    const { ctx, out } = await runDone(a, b, { ...RULES_DEFAULT, "rule.amountSign": "opposite" });
    expectCounts(out, exp);
    const c = await readClasses(ctx.written[0]!.path);
    expect(c.onlyA).toEqual(exp.rows.onlyA);
    expect(c.onlyB).toEqual(exp.rows.onlyB);
    expect(c.dupA).toEqual(exp.rows.duplicateA);
    expect(c.ambA).toEqual(exp.rows.ambiguousA);
    expect(c.ambB).toEqual(exp.rows.ambiguousB);
    const t = (out.report as { totalsCents: { a: number; b: number; difference: number } }).totalsCents;
    expect(t).toMatchObject(exp.totalsCents);
    // The planted rent check matches on amount and date only, and says so.
    expect(check(out, "weak-matches")?.status).toBe("warn");
    // The Puregold typo points at its counterpart by reference.
    const ExcelJS = (await import("exceljs")).default;
    const wb = new ExcelJS.Workbook();
    await wb.xlsx.readFile(out.outputs[0]!.path);
    const notes: string[] = [];
    wb.getWorksheet("Only in A")!.eachRow((r, n) => n > 1 && notes.push(String(r.getCell(9).value)));
    expect(notes.some((n) => n.includes("Same reference as B row") && n.includes("amount differs by"))).toBe(true);
    // The late Globe posting is pointed out as a likely pair even though it is outside the 3-day window.
    expect(notes.some((n) => n.includes("Possible match") && n.includes("date differs by 5 days"))).toBe(true);
  });

  it("a wider date tolerance matches the late Globe payment", async () => {
    const base = await runDone(a, b, { ...RULES_DEFAULT, "rule.amountSign": "opposite" });
    const wide = await runDone(a, b, { ...RULES_DEFAULT, "rule.amountSign": "opposite", "rule.dateToleranceDays": "5" });
    const m = (o: typeof base.out) => (o.report as { counts: { matched: number } }).counts.matched;
    expect(m(wide.out)).toBe(m(base.out) + 1);
  });

  it("ignoring signs is also accepted and still accounts for every row", async () => {
    const { out } = await runDone(a, b, { ...RULES_DEFAULT, "rule.amountSign": "ignore" });
    expect(check(out, "account-for-every-record")?.status).toBe("pass");
  });
});

describe("period", () => {
  it("marks rows outside the dates both files cover when the period is limited", async () => {
    const { out } = await runDone(fx("mixed-a.csv"), fx("mixed-b.csv"), { ...RULES_DEFAULT, "rule.period": "overlap" });
    expect((out.report as { rules: { period: unknown } }).rules.period).toBeTruthy();
    const all = await runDone(fx("mixed-a.csv"), fx("mixed-b.csv"), { ...RULES_DEFAULT, "rule.period": "all" });
    expect((all.out.report as { rules: { period: unknown } }).rules.period).toBeNull();
    // Classes do not change: the period only labels, so every row is still accounted for.
    expect((all.out.report as { counts: unknown }).counts).toEqual((out.report as { counts: unknown }).counts);
  });
});
